### ISSUE TITLE
[docu] Libraries and Packages List

### ISSUE THREAD

**Issue by Gidsss** [HolyShaq/prismviz#10]
## Description
Set up the initial Next.js project structure, install necessary libraries and configure basic project settings. 

## Tasks
- [x] Next.js project structure is set up with essential folders and files. 

## Libraries/Packages
1. UI and Styling
`@mui/material and @emotion/react, @emotion/styled`: Material-UI for building a responsive and modern UI.
`tailwindcss`: For utility-first CSS styling

2. Data Visualization
`chart.js and react-chartjs-2`: To create interactive charts and visualizations.
`recharts and highcharts`
`nivo.rocks`

3. File and Data Handling w/ Data Cleaning
`papaparse`: For parsing CSV files client-side.
`lodash`: For data manipulation and utility functions.

4. PDF Generation and Printing
`jspdf`: For generating PDF reports.
`html2canvas`: To convert HTML elements to canvas for use in jsPDF.
`react-to-print`: For printing React components directly.

5. State Management and Utility Packages
`react-query`: For handling data fetching and caching.
`lodash`: For data manipulation and utility functions.

6. AI Integration (Optional)
`openai`: for integrating AI features.
`dotenv`: For managing environment variables for API keys securely.
      - [API Keys](https://github.com/dan1471/FREE-openai-api-keys)

**Comment by Gidsss** [comment]
@dssrts @seegyulater @HolyShaq here yung mga packages/libraries na sa tingin ko gagamitin natin 

Note: Don't delete/close until final release

**Comment by seegyulater** [comment]
lgtm!! thanks.

**Comment by Gidsss** [comment]
Removed `pandas-js` for data cleaning and used `lodash` with `papaparse` instead 

Reason: `pandas-js`  does not fully replicate the pandas functionality from python and is deprecated
