### ISSUE TITLE
Test and verify that users can’t advance without completing each step, but can go backward freely.

### ISSUE THREAD

**Issue by Gidsss** [HolyShaq/prismviz#22]
@HolyShaq @dssrts @seegyulater check `sidebar.tsx` and resolve the logic for step completion yung issue parang visual issue lang ata idk, thanks!

**Comment by dssrts** [comment]
**Clarifications**
1. here yung cursor nag kakaprob pag galing sa upload csv, tas babalik sa cleaning
2. yung cursor naka disabled, pero na cclick parin ng user yung step 2

https://github.com/user-attachments/assets/3c194d6a-7ff1-4261-a026-24e5b4eab813

**Comment by Gidsss** [comment]
> **Clarifications**
> 
> 1. here yung cursor nag kakaprob pag galing sa upload csv, tas babalik sa cleaning
> 2. yung cursor naka disabled, pero na cclick parin ng user yung step 2
> 
>  464480899_8785615074839583_8596342007672531662_n.mp4

Yes, thank you for the clarifications!
