### ISSUE TITLE
[bug] Back and Next of Step 1 not working

### ISSUE THREAD

**Issue by HolyShaq** [HolyShaq/prismviz#30]

**Comment by Gidsss** [comment]
Remove na lang yung button na back sa step 1? Pati yung next button since pag nag upload naman file diretso naman na sa next step if naiclick "Proceed" button sa loob ng preview modal? Wdyt?

**Comment by HolyShaq** [comment]
Agree sa pagremove ng back, pero I think may value parin ung next na button.

**Comment by Gidsss** [comment]
> Agree sa pagremove ng back, pero I think may value parin ung next na button.

Anong purpose though? Diba iloload naman natin lagi yung CSV file tas makikita niya preview then automatic nagnenext?

**Comment by HolyShaq** [comment]
I think pag nag go back si user dun sa step 1 just to check ung inupload nilang file without clearing or uploading a new one, they can still go to the next step gamit ung next button without having to click for preview then proceed.

Maybe a better implementation would be, lilitaw lang si next button pag may naka-upload ng file.

**Comment by Gidsss** [comment]
> I think pag nag go back si user dun sa step 1 just to check ung inupload nilang file without clearing or uploading a new one, they can still go to the next step gamit ung next button without having to click for preview then proceed.
> 
> Maybe a better implementation would be, lilitaw lang si next button pag may naka-upload ng file.

Yeah ayan pala kapag may file lang, sounds good!
