### ISSUE TITLE
Design a logo and create responsive variants (SVG format preferred).

### ISSUE THREAD

**Issue by seegyulater** [HolyShaq/prismviz#32]

**Comment by seegyulater** [comment]
Cinonvert ko yung PNG na design na logo ni jayson to ICO and uploaded na rin sha sa /public kaso di ko sha mapagana sa code IDKKK gawin ko muna issue to!!

**Comment by Gidsss** [comment]
Fixed (added the ico link directly in head of `layout.tsx` so its included in all pages):

![image](https://github.com/user-attachments/assets/cad02702-4246-4194-8333-20d24bc60c01)

Icon in browser:

![image](https://github.com/user-attachments/assets/c1f08b8c-8dee-4e47-941b-f96acb8acb1e)


@seegyulater add mo na lang din sa branch mo eto sa `layout.tsx` yan thanks!
